spring:
  datasource:
    url: ${MYSQL_DB_URL:jdbc:mysql://localhost:3306/demo-spring?createDatabaseIfNotExist=true}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME:root}
    password: ${MYSQL_DB_PASSWORD:dnstuff@dnskroz}
  jpa:
    hibernate.ddl-auto: create-drop